### ISSUE TITLE
Missing configure and Makefile doesn't have build or install steps

### ISSUE THREAD

**Issue by protosam** [sbalneav/libnss-external#3]
Title pretty much says it all. I'm unsure if this is even compile-able, without guessing how you intended for this to compile @sbalneav

**Comment by mattsoftware** [comment]
If it helps, I generated a pull request for an rpm build spec file which has the process for building the package in it... https://github.com/sbalneav/libnss-external/pull/1/commits/6119165fe0d728e4a8221b0e3159e6db5566d9e9

**Comment by protosam** [comment]
@mattsoftware thanks for that rpm build spec, it's quite handy. 
@sbalneav thanks, I didn't know to run that. It generated the necessary files.

I'm kindof stuck though, probably due to a misunderstanding on my part.

I have just have these scripts setup as a small test:
```
[root@app01 nss-external]# pwd
/etc/nss-external

[root@app01 nss-external]# cat group
#!/bin/bash
cat /etc/nss-external/group_file
echo $0 $@ >> /tmp/nss-runlog.log

[root@app01 nss-external]# cat passwd
#!/bin/bash
cat /etc/nss-external/passwd_file
echo $0 $@ >> /tmp/nss-runlog.log

[root@app01 nss-external]# cat shadow
#!/bin/bash
cat /etc/nss-external/shadow_file
echo $0 $@ >> /tmp/nss-runlog.log
```

Those files are entries of a user I pulled from the passwd, shadow, and group files on another server. 

The file /tmp/nss-runlog.log doesn't get appended to from running `getent group`, `getent passwd`, or anything in my tests.

I've tried throwing the library file in `/usr/lib64/libnss_external.so` as well as leaving it + symlinks in `/usr/lib`. 

My nsswitch.conf file is configured like this:
```
passwd:     files external sss
shadow:     files external sss
group:      files external sss
```

I'm clearly missing something. Maybe I could get some direction on this? I'm testing this on CentOS 7 and plan to test it out on Debian 9 next. Since Matt threw a spec file for rpm, I'll contribute some dpkg build scripts if I can get this working.
